### ISSUE TITLE
startup files for CM0 present in the repo

### ISSUE THREAD

**Issue by atsju** [STMicroelectronics/cmsis_device_wb#1] opened 2021-07-22 12:41 UTC
There are [startup files for CM0 core](https://github.com/STMicroelectronics/cmsis_device_wb/blob/master/Source/Templates/gcc/startup_stm32wb10xx_cm0.s) in the repository although they are not present in [cube repository](https://github.com/STMicroelectronics/STM32CubeWB).

This is incoherent and WB policy is that the core M0 part is not available for final customer. The libraries are written, generated and signed by ST.

**Comment by RKOUSTM** [comment] 2021-07-29 12:54
Hi @atsju,

Thank you for your contribution. It seems we missed this issue you have sent since a while.  It has been transferred to our development teams for analysis. We will get back to you as soon as we have an answer.

With regards,

**Comment by atsju** [comment] 2021-07-29 13:08
Thank you. No problem for delay, I just mention everything I see when I see it to help you improve code quality.
Maybe you have also missed https://github.com/STMicroelectronics/STM32CubeWB/issues/35 and https://github.com/STMicroelectronics/STM32CubeWB/issues/36

**Comment by RKOUSTM** [comment] 2021-07-29 13:13
Hi @atsju,

Sorry for the delay it may take sometimes to answer.

Thank you again for this contribution and thank you in advance for your patience.

 with regards,

**Comment by RKOUSTM** [comment] 2021-08-04 07:58
Hi @atsju,

Thank you for your contribution. The issue you pointed out has been confirmed. An internal tracker has been logged and a fix will be implemented and made available in the frame of a future release.

Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment] 2021-08-04 08:00
ST Internal Reference: 111416

**Closed as completed** 2021-12-07 18:24 UTC
Labels: enhancement, internal bug tracker, cmsis
